import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import snapShots from '../public/snapshots';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Three Fiber Demo</title>
        <meta name="baidu-site-verification" content="code-l8uWEyCz8q" />
        <meta name="description" content="Generated by Simon-Bin" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {snapShots.map(img=>{
          return <Link href={`/${img}`} key={img} passHref>
            <Image className={styles.snapshot} src={`/snapshots/${img}.png`} width={`200`} height="160" alt={img}/>
            </Link>
        })}
      </main>
    </div>
  )
}

export default Home
